export const navigationStrings = {
  HOME: 'HOME',
  SPLASH: 'SPLASH',
  DRAWER: 'DRAWER',
  SUBSCRIPTION: 'SUBSCRIPTION',
  ACCOUNT: 'ACCOUNT',
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  FAQ: 'FAQ',
  HELP: 'HELP',
  INVITE: 'INVITE',
  HISTORY: 'HISTORY',
  FORGET_PASSWORD: 'FORGET_PASSWORD',
};
