export const ASK_QUESTION_SHEET = 'ASK_QUESTION_SHEET';
export const HISTORY_SHEET = 'HISTORY_SHEET';
export const RESULT_SHEET = 'RESULT_SHEET';
export const GET_SUBSCRIPTION_SHEET = 'GET_SUBSCRIPTION_SHEET';
